// Code generated by mkbuiltin.go. DO NOT EDIT.

package gc

import "cmd/compile/internal/types"

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"newobject", funcTag, 4},
	{"panicindex", funcTag, 5},
	{"panicslice", funcTag, 5},
	{"panicdivide", funcTag, 5},
	{"throwinit", funcTag, 5},
	{"panicwrap", funcTag, 7},
	{"gopanic", funcTag, 9},
	{"gorecover", funcTag, 12},
	{"goschedguarded", funcTag, 5},
	{"printbool", funcTag, 14},
	{"printfloat", funcTag, 16},
	{"printint", funcTag, 18},
	{"printhex", funcTag, 20},
	{"printuint", funcTag, 20},
	{"printcomplex", funcTag, 22},
	{"printstring", funcTag, 24},
	{"printpointer", funcTag, 25},
	{"printiface", funcTag, 25},
	{"printeface", funcTag, 25},
	{"printslice", funcTag, 25},
	{"printnl", funcTag, 5},
	{"printsp", funcTag, 5},
	{"printlock", funcTag, 5},
	{"printunlock", funcTag, 5},
	{"concatstring2", funcTag, 28},
	{"concatstring3", funcTag, 29},
	{"concatstring4", funcTag, 30},
	{"concatstring5", funcTag, 31},
	{"concatstrings", funcTag, 33},
	{"cmpstring", funcTag, 35},
	{"eqstring", funcTag, 36},
	{"intstring", funcTag, 39},
	{"slicebytetostring", funcTag, 41},
	{"slicebytetostringtmp", funcTag, 42},
	{"slicerunetostring", funcTag, 45},
	{"stringtoslicebyte", funcTag, 46},
	{"stringtoslicerune", funcTag, 49},
	{"decoderune", funcTag, 50},
	{"slicecopy", funcTag, 52},
	{"slicestringcopy", funcTag, 53},
	{"convI2I", funcTag, 54},
	{"convT2E", funcTag, 55},
	{"convT2E16", funcTag, 55},
	{"convT2E32", funcTag, 55},
	{"convT2E64", funcTag, 55},
	{"convT2Estring", funcTag, 55},
	{"convT2Eslice", funcTag, 55},
	{"convT2Enoptr", funcTag, 55},
	{"convT2I", funcTag, 55},
	{"convT2I16", funcTag, 55},
	{"convT2I32", funcTag, 55},
	{"convT2I64", funcTag, 55},
	{"convT2Istring", funcTag, 55},
	{"convT2Islice", funcTag, 55},
	{"convT2Inoptr", funcTag, 55},
	{"assertE2I", funcTag, 54},
	{"assertE2I2", funcTag, 56},
	{"assertI2I", funcTag, 54},
	{"assertI2I2", funcTag, 56},
	{"panicdottypeE", funcTag, 57},
	{"panicdottypeI", funcTag, 57},
	{"panicnildottype", funcTag, 58},
	{"ifaceeq", funcTag, 61},
	{"efaceeq", funcTag, 61},
	{"makemap", funcTag, 63},
	{"mapaccess1", funcTag, 64},
	{"mapaccess1_fast32", funcTag, 65},
	{"mapaccess1_fast64", funcTag, 65},
	{"mapaccess1_faststr", funcTag, 65},
	{"mapaccess1_fat", funcTag, 66},
	{"mapaccess2", funcTag, 67},
	{"mapaccess2_fast32", funcTag, 68},
	{"mapaccess2_fast64", funcTag, 68},
	{"mapaccess2_faststr", funcTag, 68},
	{"mapaccess2_fat", funcTag, 69},
	{"mapassign", funcTag, 64},
	{"mapassign_fast32", funcTag, 65},
	{"mapassign_fast64", funcTag, 65},
	{"mapassign_faststr", funcTag, 65},
	{"mapiterinit", funcTag, 70},
	{"mapdelete", funcTag, 70},
	{"mapdelete_fast32", funcTag, 71},
	{"mapdelete_fast64", funcTag, 71},
	{"mapdelete_faststr", funcTag, 71},
	{"mapiternext", funcTag, 72},
	{"makechan", funcTag, 74},
	{"chanrecv1", funcTag, 76},
	{"chanrecv2", funcTag, 77},
	{"chansend1", funcTag, 79},
	{"closechan", funcTag, 25},
	{"writeBarrier", varTag, 81},
	{"writebarrierptr", funcTag, 82},
	{"typedmemmove", funcTag, 83},
	{"typedmemclr", funcTag, 84},
	{"typedslicecopy", funcTag, 85},
	{"selectnbsend", funcTag, 86},
	{"selectnbrecv", funcTag, 87},
	{"selectnbrecv2", funcTag, 89},
	{"newselect", funcTag, 90},
	{"selectsend", funcTag, 91},
	{"selectrecv", funcTag, 92},
	{"selectdefault", funcTag, 58},
	{"selectgo", funcTag, 93},
	{"block", funcTag, 5},
	{"makeslice", funcTag, 95},
	{"makeslice64", funcTag, 96},
	{"growslice", funcTag, 97},
	{"memmove", funcTag, 98},
	{"memclrNoHeapPointers", funcTag, 99},
	{"memclrHasPointers", funcTag, 99},
	{"memequal", funcTag, 100},
	{"memequal8", funcTag, 101},
	{"memequal16", funcTag, 101},
	{"memequal32", funcTag, 101},
	{"memequal64", funcTag, 101},
	{"memequal128", funcTag, 101},
	{"int64div", funcTag, 102},
	{"uint64div", funcTag, 103},
	{"int64mod", funcTag, 102},
	{"uint64mod", funcTag, 103},
	{"float64toint64", funcTag, 104},
	{"float64touint64", funcTag, 105},
	{"float64touint32", funcTag, 107},
	{"int64tofloat64", funcTag, 108},
	{"uint64tofloat64", funcTag, 109},
	{"uint32tofloat64", funcTag, 110},
	{"complex128div", funcTag, 111},
	{"racefuncenter", funcTag, 112},
	{"racefuncexit", funcTag, 5},
	{"raceread", funcTag, 112},
	{"racewrite", funcTag, 112},
	{"racereadrange", funcTag, 113},
	{"racewriterange", funcTag, 113},
	{"msanread", funcTag, 113},
	{"msanwrite", funcTag, 113},
	{"support_popcnt", varTag, 13},
}

func runtimeTypes() []*types.Type {
	var typs [114]*types.Type
	typs[0] = types.Bytetype
	typs[1] = types.NewPtr(typs[0])
	typs[2] = types.Types[TANY]
	typs[3] = types.NewPtr(typs[2])
	typs[4] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[5] = functype(nil, nil, nil)
	typs[6] = types.Types[TUINT8]
	typs[7] = functype(nil, []*Node{anonfield(typs[6])}, nil)
	typs[8] = types.Types[TINTER]
	typs[9] = functype(nil, []*Node{anonfield(typs[8])}, nil)
	typs[10] = types.Types[TINT32]
	typs[11] = types.NewPtr(typs[10])
	typs[12] = functype(nil, []*Node{anonfield(typs[11])}, []*Node{anonfield(typs[8])})
	typs[13] = types.Types[TBOOL]
	typs[14] = functype(nil, []*Node{anonfield(typs[13])}, nil)
	typs[15] = types.Types[TFLOAT64]
	typs[16] = functype(nil, []*Node{anonfield(typs[15])}, nil)
	typs[17] = types.Types[TINT64]
	typs[18] = functype(nil, []*Node{anonfield(typs[17])}, nil)
	typs[19] = types.Types[TUINT64]
	typs[20] = functype(nil, []*Node{anonfield(typs[19])}, nil)
	typs[21] = types.Types[TCOMPLEX128]
	typs[22] = functype(nil, []*Node{anonfield(typs[21])}, nil)
	typs[23] = types.Types[TSTRING]
	typs[24] = functype(nil, []*Node{anonfield(typs[23])}, nil)
	typs[25] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[26] = types.NewArray(typs[0], 32)
	typs[27] = types.NewPtr(typs[26])
	typs[28] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[29] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[23]), anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[30] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[23]), anonfield(typs[23]), anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[31] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[23]), anonfield(typs[23]), anonfield(typs[23]), anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[32] = types.NewSlice(typs[23])
	typs[33] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[32])}, []*Node{anonfield(typs[23])})
	typs[34] = types.Types[TINT]
	typs[35] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[34])})
	typs[36] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[13])})
	typs[37] = types.NewArray(typs[0], 4)
	typs[38] = types.NewPtr(typs[37])
	typs[39] = functype(nil, []*Node{anonfield(typs[38]), anonfield(typs[17])}, []*Node{anonfield(typs[23])})
	typs[40] = types.NewSlice(typs[0])
	typs[41] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[40])}, []*Node{anonfield(typs[23])})
	typs[42] = functype(nil, []*Node{anonfield(typs[40])}, []*Node{anonfield(typs[23])})
	typs[43] = types.Runetype
	typs[44] = types.NewSlice(typs[43])
	typs[45] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[44])}, []*Node{anonfield(typs[23])})
	typs[46] = functype(nil, []*Node{anonfield(typs[27]), anonfield(typs[23])}, []*Node{anonfield(typs[40])})
	typs[47] = types.NewArray(typs[43], 32)
	typs[48] = types.NewPtr(typs[47])
	typs[49] = functype(nil, []*Node{anonfield(typs[48]), anonfield(typs[23])}, []*Node{anonfield(typs[44])})
	typs[50] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[34])}, []*Node{anonfield(typs[43]), anonfield(typs[34])})
	typs[51] = types.Types[TUINTPTR]
	typs[52] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2]), anonfield(typs[51])}, []*Node{anonfield(typs[34])})
	typs[53] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[34])})
	typs[54] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[55] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[56] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2]), anonfield(typs[13])})
	typs[57] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[1])}, nil)
	typs[58] = functype(nil, []*Node{anonfield(typs[1])}, nil)
	typs[59] = types.NewPtr(typs[51])
	typs[60] = types.Types[TUNSAFEPTR]
	typs[61] = functype(nil, []*Node{anonfield(typs[59]), anonfield(typs[60]), anonfield(typs[60])}, []*Node{anonfield(typs[13])})
	typs[62] = types.NewMap(typs[2], typs[2])
	typs[63] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[17]), anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[62])})
	typs[64] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3])}, []*Node{anonfield(typs[3])})
	typs[65] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[66] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[67] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3])}, []*Node{anonfield(typs[3]), anonfield(typs[13])})
	typs[68] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[13])})
	typs[69] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3]), anonfield(typs[13])})
	typs[70] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[3])}, nil)
	typs[71] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[62]), anonfield(typs[2])}, nil)
	typs[72] = functype(nil, []*Node{anonfield(typs[3])}, nil)
	typs[73] = types.NewChan(typs[2], types.Cboth)
	typs[74] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[17])}, []*Node{anonfield(typs[73])})
	typs[75] = types.NewChan(typs[2], types.Crecv)
	typs[76] = functype(nil, []*Node{anonfield(typs[75]), anonfield(typs[3])}, nil)
	typs[77] = functype(nil, []*Node{anonfield(typs[75]), anonfield(typs[3])}, []*Node{anonfield(typs[13])})
	typs[78] = types.NewChan(typs[2], types.Csend)
	typs[79] = functype(nil, []*Node{anonfield(typs[78]), anonfield(typs[3])}, nil)
	typs[80] = types.NewArray(typs[0], 3)
	typs[81] = tostruct([]*Node{namedfield("enabled", typs[13]), namedfield("pad", typs[80]), namedfield("needed", typs[13]), namedfield("cgo", typs[13]), namedfield("alignme", typs[19])})
	typs[82] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[2])}, nil)
	typs[83] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3]), anonfield(typs[3])}, nil)
	typs[84] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, nil)
	typs[85] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2]), anonfield(typs[2])}, []*Node{anonfield(typs[34])})
	typs[86] = functype(nil, []*Node{anonfield(typs[78]), anonfield(typs[3])}, []*Node{anonfield(typs[13])})
	typs[87] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[75])}, []*Node{anonfield(typs[13])})
	typs[88] = types.NewPtr(typs[13])
	typs[89] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[88]), anonfield(typs[75])}, []*Node{anonfield(typs[13])})
	typs[90] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[17]), anonfield(typs[10])}, nil)
	typs[91] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[78]), anonfield(typs[3])}, nil)
	typs[92] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[75]), anonfield(typs[3]), anonfield(typs[88])}, nil)
	typs[93] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[34])})
	typs[94] = types.NewSlice(typs[2])
	typs[95] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[34]), anonfield(typs[34])}, []*Node{anonfield(typs[94])})
	typs[96] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[17]), anonfield(typs[17])}, []*Node{anonfield(typs[94])})
	typs[97] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[94]), anonfield(typs[34])}, []*Node{anonfield(typs[94])})
	typs[98] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[51])}, nil)
	typs[99] = functype(nil, []*Node{anonfield(typs[60]), anonfield(typs[51])}, nil)
	typs[100] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[51])}, []*Node{anonfield(typs[13])})
	typs[101] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[13])})
	typs[102] = functype(nil, []*Node{anonfield(typs[17]), anonfield(typs[17])}, []*Node{anonfield(typs[17])})
	typs[103] = functype(nil, []*Node{anonfield(typs[19]), anonfield(typs[19])}, []*Node{anonfield(typs[19])})
	typs[104] = functype(nil, []*Node{anonfield(typs[15])}, []*Node{anonfield(typs[17])})
	typs[105] = functype(nil, []*Node{anonfield(typs[15])}, []*Node{anonfield(typs[19])})
	typs[106] = types.Types[TUINT32]
	typs[107] = functype(nil, []*Node{anonfield(typs[15])}, []*Node{anonfield(typs[106])})
	typs[108] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[15])})
	typs[109] = functype(nil, []*Node{anonfield(typs[19])}, []*Node{anonfield(typs[15])})
	typs[110] = functype(nil, []*Node{anonfield(typs[106])}, []*Node{anonfield(typs[15])})
	typs[111] = functype(nil, []*Node{anonfield(typs[21]), anonfield(typs[21])}, []*Node{anonfield(typs[21])})
	typs[112] = functype(nil, []*Node{anonfield(typs[51])}, nil)
	typs[113] = functype(nil, []*Node{anonfield(typs[51]), anonfield(typs[51])}, nil)
	return typs[:]
}
