// Copyright 2016 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build ignore

// TODO(gri) Make this a more generally useful tool?

// The printfix command is a utility to enumerate, verify,
// and automatically rewrite format strings for the package
// in this directory.
//
// printfix finds all potential (Printf, etc.) format strings.
// If they are used in a call, the format verbs are verified
// based on the matching argument type against a precomputed
// table of valid formats (formatMapping, below). The table
// can be used to automatically rewrite format strings with
// the -u flag.
//
// Run as: go run printfix.go {flags}
//
// Flags:
//	-t  test that format specifiers are valid
//	-u  update format specifiers per formatMapping
//	-v  verbose mode
//
// A new formatMapping can be generated by running in -v mode.
//
// BUGS: printfix cannot handle computed format strings yet.
//       Instead it enumerates them with warnings.
//
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"io/ioutil"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

var (
	test    = flag.Bool("t", false, "test formats")
	update  = flag.Bool("u", false, "update files")
	verbose = flag.Bool("v", false, "verbose")
)

var (
	fset     = token.NewFileSet() // file set for all processed files
	typedPkg *types.Package       // the package we are type-checking
	exitcode int
)

// A CallSite describes a function call that appears to contain
// a format string.
type CallSite struct {
	file  int           // buildPkg.GoFiles index
	call  *ast.CallExpr // call containing the format string
	lit   *ast.BasicLit // format literal
	str   string        // unquoted format string
	types []string      // argument types
}

func main() {
	flag.Parse()

	// determine .go files
	buildPkg, err := build.ImportDir(".", 0)
	if err != nil {
		log.Fatal(err)
	}

	// parse all files
	files := make([]*ast.File, len(buildPkg.GoFiles))
	for i, filename := range buildPkg.GoFiles {
		f, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			log.Fatal(err)
		}
		files[i] = f
	}

	// typecheck package
	conf := types.Config{Importer: importer.Default()}
	etypes := make(map[ast.Expr]types.TypeAndValue)
	typedPkg, err = conf.Check("some_path", fset, files, &types.Info{Types: etypes})
	if err != nil {
		log.Fatal(err)
	}

	// collect all potential format strings (for extra verification later)
	potentialFormats := make(map[*ast.BasicLit]bool)
	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			if s, ok := stringLit(n); ok && isFormat(s) {
				potentialFormats[n.(*ast.BasicLit)] = true
			}
			return true
		})
	}

	// collect all formats/arguments of calls with format strings
	var callSites []*CallSite
	for index, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			if call, ok := n.(*ast.CallExpr); ok {
				// ignore blackisted functions
				if functionBlacklisted[nodeString(call.Fun)] {
					return true
				}
				// determine if an argument looks like a format string
				for i, arg := range call.Args {
					if s, ok := stringLit(arg); ok && isFormat(s) {
						// found argument that looks like a format string;
						// make sure we have enough arguments
						n := formatArgs(s)
						if i+1+n > len(call.Args) {
							errorf("%s: not enough format args (blacklist %s?)", posString(call), nodeString(call.Fun))
							break // ignore this call
						}
						// assume last n arguments are to be formatted;
						// determine their types
						argTypes := make([]string, n)
						for i, arg := range call.Args[len(call.Args)-n:] {
							if tv, ok := etypes[arg]; ok {
								argTypes[i] = typeString(tv.Type)
							}
						}
						// collect call site
						callSites = append(callSites, &CallSite{
							file:  index,
							call:  call,
							lit:   arg.(*ast.BasicLit),
							str:   s,
							types: argTypes,
						})
						break // at most of format per argument list
					}
				}
			}
			return true
		})
	}

	// test and rewrite formats
	keys := make(map[string]bool)
	dirty := false                         // dirty means some files have been modified
	dirtyFiles := make([]bool, len(files)) // dirtyFiles[i] means file i has been modified
	for _, p := range callSites {
		out := formatReplace(p.str, func(index int, in string) string {
			if in == "*" {
				return in
			}
			typ := p.types[index]
			key := typ + " " + in // e.g., "*Node %n"
			keys[key] = true
			out, found := formatMapping[key]
			if !found && *test {
				errorf("%s: unknown format %q for %s argument", posString(p.lit), in, typ)
			}
			if out == "" {
				out = in
			}
			return out
		})

		// replace existing format literal if it changed
		if out != p.str {
			if *verbose {
				fmt.Printf("%s:\n\t   %q\n\t=> %q\n", posString(p.lit), p.str, out)
			}
			index := -1
			for i, arg := range p.call.Args {
				if p.lit == arg {
					index = i
					break
				}
			}
			if index < 0 {
				panic("internal error: matching argument not found")
			}
			new := *p.lit                  // make a copy
			new.Value = strconv.Quote(out) // this may introduce "-quotes where there were `-quotes
			p.call.Args[index] = &new
			dirty = true
			dirtyFiles[p.file] = true // mark file as changed
		}
	}

	// write dirty files back
	if dirty && *update {
		for i, d := range dirtyFiles {
			if !d {
				continue
			}
			filename := buildPkg.GoFiles[i]
			var buf bytes.Buffer
			if err := format.Node(&buf, fset, files[i]); err != nil {
				errorf("WARNING: formatting %s failed: %v", filename, err)
				continue
			}
			if err := ioutil.WriteFile(filename, buf.Bytes(), 0x666); err != nil {
				errorf("WARNING: writing %s failed: %v", filename, err)
				continue
			}
			fmt.Println(filename)
		}
	}

	// report all function names containing a format string
	if len(callSites) > 0 && *verbose {
		set := make(map[string]bool)
		for _, p := range callSites {
			set[nodeString(p.call.Fun)] = true
		}
		var list []string
		for s := range set {
			list = append(list, s)
		}
		fmt.Println("\nFunctions")
		printList(list)
	}

	// report all keys found
	if len(keys) > 0 && *verbose {
		var list []string
		for s := range keys {
			list = append(list, fmt.Sprintf("%q: \"\",", s))
		}
		fmt.Println("\nvar formatMapping = map[string]string{")
		printList(list)
		fmt.Println("}")
	}

	// all format literals must in the potentialFormats set (self-verification)
	for _, p := range callSites {
		if potentialFormats[p.lit] {
			// ok
			delete(potentialFormats, p.lit)
		} else {
			// this should never happen
			panic(fmt.Sprintf("internal error: format string not found (%s)", posString(p.lit)))
		}
	}

	// if we have any strings left, we may need to update them manually
	if len(potentialFormats) > 0 && *update {
		var list []string
		for lit := range potentialFormats {
			list = append(list, fmt.Sprintf("%s: %s", posString(lit), nodeString(lit)))
		}
		fmt.Println("\nWARNING: Missed format strings")
		printList(list)
	}

	os.Exit(exitcode)
}

func errorf(format string, args ...interface{}) {
	if len(format) > 0 && format[len(format)-1] != '\n' {
		format += "\n"
	}
	fmt.Printf(format, args...)
	exitcode = 1
}

// printList prints list in sorted order.
func printList(list []string) {
	sort.Strings(list)
	for _, s := range list {
		fmt.Println("\t", s)
	}
}

// posString returns a string representation of n's position
// in the form filename:line:col: .
func posString(n ast.Node) string {
	if n == nil {
		return ""
	}
	return fset.Position(n.Pos()).String()
}

// nodeString returns a string representation of n.
func nodeString(n ast.Node) string {
	var buf bytes.Buffer
	if err := format.Node(&buf, fset, n); err != nil {
		log.Fatal(err)
	}
	return buf.String()
}

// typeString returns a string representation of t.
func typeString(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		// don't qualify type names of the typed package
		if pkg == typedPkg {
			return ""
		}
		return pkg.Path()
	})
}

// stringLit returns the unquoted string value and true if
// n represents a string literal; otherwise it returns ""
// and false.
func stringLit(n ast.Node) (string, bool) {
	if lit, ok := n.(*ast.BasicLit); ok && lit.Kind == token.STRING {
		s, err := strconv.Unquote(lit.Value)
		if err != nil {
			log.Fatal(err) // should not happen with correct ASTs
		}
		return s, true
	}
	return "", false
}

// formatIter iterates through the string s in increasing
// index order and calls f for each format specifier '%..v'.
// The arguments for f describe the specifier's index range.
// If a format specifier contains a  "*", f is called with
// the index range for "*" alone, before being called for
// the entire specifier. The result of f is the index of
// the rune at which iteration continues.
func formatIter(s string, f func(i, j int) int) {
	i := 0     // string index
	var r rune // current rune

	next := func() {
		r1, w := utf8.DecodeRuneInString(s[i:])
		if w == 0 {
			r1 = -1 // signal end-of-string
		}
		r = r1
		i += w
	}

	skipFlags := func() {
		for r == ' ' || r == '#' || r == '+' || r == '-' || r == '0' {
			next()
		}
	}

	skipDigits := func() {
		if r == '*' {
			i = f(i-1, i)
			next()
			return
		}
		for '0' <= r && r <= '9' {
			next()
		}
	}

	for next(); r >= 0; next() {
		if r == '%' {
			i0 := i
			next()
			skipFlags()
			skipDigits()
			if r == '.' {
				next()
				skipDigits()
			}
			// accept any char except for % as format flag
			if r == '%' {
				if i-i0 == 1 {
					continue // skip "%%"
				}
				log.Fatalf("incorrect format string: %s", s)
			}
			if r >= 0 {
				i = f(i0-1, i)
			}
		}
	}
}

// isFormat returns true if s contains format specifiers.
func isFormat(s string) (yes bool) {
	formatIter(s, func(i, j int) int {
		yes = true
		return len(s) // stop iteration
	})
	return
}

// oneFormat returns true if s is exactly one format specifier.
func oneFormat(s string) (yes bool) {
	formatIter(s, func(i, j int) int {
		yes = i == 0 && j == len(s)
		return j
	})
	return
}

// formatArgs counts the number of format specifiers in s.
func formatArgs(s string) int {
	count := 0
	formatIter(s, func(i, j int) int {
		count++
		return j
	})
	return count
}

// formatReplace replaces the i'th format specifier s in the incoming
// string in with the result of f(i, s) and returns the new string.
func formatReplace(in string, f func(i int, s string) string) string {
	var buf []byte
	i0 := 0
	index := 0
	formatIter(in, func(i, j int) int {
		if sub := in[i:j]; sub != "*" { // ignore calls for "*" width/length specifiers
			buf = append(buf, in[i0:i]...)
			buf = append(buf, f(index, sub)...)
			i0 = j
		}
		index++
		return j
	})
	return string(append(buf, in[i0:]...))
}

func init() {
	// verify that formatMapping entries are correctly formatted
	for key, val := range formatMapping {
		// key must be "typename format" (format may be "*")
		i := strings.Index(key, " ")
		if i < 0 || key[i+1:] != "*" && !oneFormat(key[i+1:]) {
			log.Fatalf("incorrect formatMapping key: %q", key)
		}
		// val must be "format" or ""
		if val != "" && !oneFormat(val) {
			log.Fatalf("incorrect formatMapping key: %q", key)
		}
	}
}

// functionBlacklisted is the set of functions which are known to
// have format-like arguments but which don't do any formatting
// and thus can be ignored.
var functionBlacklisted = map[string]bool{
	"len": true,
	"strings.ContainsRune": true,
}

// formatMapping entries are of the form "typename oldformat" -> "newformat".
// An absent entry means that the format is not recognized as correct in test
// mode.
// An empty new format means that the existing format should remain unchanged.
// To generate a new table, run: printfix -t
var formatMapping = map[string]string{
	"*Bits %v":                           "",
	"*Field %p":                          "",
	"*Field %v":                          "",
	"*Mpflt %v":                          "",
	"*Mpint %v":                          "",
	"*Node %p":                           "",
	"*Node %s":                           "",
	"*Node %v":                           "",
	"*Sym %p":                            "",
	"*Sym %s":                            "",
	"*Sym %v":                            "",
	"*Type %p":                           "",
	"*Type %s":                           "",
	"*Type %v":                           "",
	"*cmd/compile/internal/big.Int %#x":  "",
	"*cmd/compile/internal/ssa.Block %v": "",
	"*cmd/compile/internal/ssa.Func %s":  "",
	"*cmd/compile/internal/ssa.Value %s": "",
	"*cmd/compile/internal/ssa.Value %v": "",
	"*cmd/internal/obj.Addr %v":          "",
	"*cmd/internal/obj.Prog %p":          "",
	"*cmd/internal/obj.Prog %s":          "",
	"*cmd/internal/obj.Prog %v":          "",
	"Class %d":                           "",
	"Ctype %d":                           "",
	"Ctype %v":                           "",
	"EType %d":                           "",
	"EType %s":                           "",
	"EType %v":                           "",
	"Level %d":                           "",
	"Level %v":                           "",
	"Nodes %v":                           "",
	"Op %#v":                             "",
	"Op %d":                              "",
	"Op %s":                              "",
	"Op %v":                              "",
	"Val %v":                             "",
	"[16]byte %x":                        "",
	"[]*Node %v":                         "",
	"[]byte %s":                          "",
	"[]byte %x":                          "",
	"bool %t":                            "",
	"bool %v":                            "",
	"byte %02x":                          "",
	"byte %c":                            "",
	"cmd/compile/internal/ssa.Location %v":         "",
	"cmd/compile/internal/ssa.Type %s":             "",
	"cmd/compile/internal/syntax.Expr %#v":         "",
	"error %v":                                     "",
	"float64 %.2f":                                 "",
	"float64 %.6g":                                 "",
	"float64 %g":                                   "",
	"fmt.Stringer %T":                              "",
	"int %-12d":                                    "",
	"int %-2d":                                     "",
	"int %-6d":                                     "",
	"int %-8o":                                     "",
	"int %2d":                                      "",
	"int %6d":                                      "",
	"int %c":                                       "",
	"int %d":                                       "",
	"int %v":                                       "",
	"int %x":                                       "",
	"int16 %2d":                                    "",
	"int16 %d":                                     "",
	"int32 %4d":                                    "",
	"int32 %5d":                                    "",
	"int32 %d":                                     "",
	"int32 %v":                                     "",
	"int64 %+d":                                    "",
	"int64 %-10d":                                  "",
	"int64 %d":                                     "",
	"int64 %v":                                     "",
	"int8 %d":                                      "",
	"interface{} %#v":                              "",
	"interface{} %T":                               "",
	"interface{} %v":                               "",
	"map[*Node]*cmd/compile/internal/ssa.Value %v": "",
	"reflect.Type %s":                              "",
	"rune %#U":                                     "",
	"rune %c":                                      "",
	"rune %d":                                      "",
	"string %-16s":                                 "",
	"string %.*s":                                  "",
	"string %q":                                    "",
	"string %s":                                    "",
	"string %v":                                    "",
	"time.Duration %d":                             "",
	"uint %.4d":                                    "",
	"uint %04x":                                    "",
	"uint16 %d":                                    "",
	"uint16 %v":                                    "",
	"uint32 %#x":                                   "",
	"uint32 %d":                                    "",
	"uint64 %#x":                                   "",
	"uint64 %08x":                                  "",
	"uint8 %d":                                     "",
}
