<<<<<<< HEAD   (c6d3d0 [dev.typeparams] go/types: fix the type parameter index in a)
=======
// Code generated by gengoos.go using 'go generate'. DO NOT EDIT.

//go:build armbe
// +build armbe

package sys

const GOARCH = `armbe`

const Goarch386 = 0
const GoarchAmd64 = 0
const GoarchAmd64p32 = 0
const GoarchArm = 0
const GoarchArmbe = 1
const GoarchArm64 = 0
const GoarchArm64be = 0
const GoarchPpc64 = 0
const GoarchPpc64le = 0
const GoarchLoong64 = 0
const GoarchMips = 0
const GoarchMipsle = 0
const GoarchMips64 = 0
const GoarchMips64le = 0
const GoarchMips64p32 = 0
const GoarchMips64p32le = 0
const GoarchPpc = 0
const GoarchRiscv = 0
const GoarchRiscv64 = 0
const GoarchS390 = 0
const GoarchS390x = 0
const GoarchSparc = 0
const GoarchSparc64 = 0
const GoarchWasm = 0
>>>>>>> BRANCH (c8f4e6 spec: correct example comment in Conversions from slice to a)
