// auto generated by go tool dist

package sys

const DefaultGoroot = `/Users/matloob/go`
const TheVersion = `devel +644baf7 Wed Nov 11 12:47:43 2015 -0500`
const Goexperiment = ``
const StackGuardMultiplier = 1

var BuildVersion = TheVersion
