// auto generated by go tool dist

package sys

const DefaultGoroot = `/Users/matloob/go`
const TheVersion = `devel +e1a40e8 Wed Nov 11 12:45:44 2015 -0500`
const Goexperiment = ``
const StackGuardMultiplier = 1

var BuildVersion = TheVersion
