// Code generated by gengoarch.go using 'go generate'. DO NOT EDIT.

//go:build 386
// +build 386

package goarch

const GOARCH = `386`

const I386 = 1
const Amd64 = 0
const Amd64p32 = 0
const Arm = 0
const Armbe = 0
const Arm64 = 0
const Arm64be = 0
const Ppc64 = 0
const Ppc64le = 0
const Mips = 0
const Mipsle = 0
const Mips64 = 0
const Mips64le = 0
const Mips64p32 = 0
const Mips64p32le = 0
const Ppc = 0
const Riscv = 0
const Riscv64 = 0
const S390 = 0
const S390x = 0
const Sparc = 0
const Sparc64 = 0
const Wasm = 0
