// Code generated by "stringer -type Delim"; DO NOT EDIT

package parse

import "fmt"

const _Delim_name = "DelimNoneDelimDoubleQuoteDelimSingleQuoteDelimSpaceOrTagEnd"

var _Delim_index = [...]uint8{0, 9, 25, 41, 59}

func (i Delim) String() string {
	if i >= Delim(len(_Delim_index)-1) {
		return fmt.Sprintf("Delim(%d)", i)
	}
	return _Delim_name[_Delim_index[i]:_Delim_index[i+1]]
}
