// Code generated by "stringer -type JSCtx"; DO NOT EDIT

package parse

import "fmt"

const _JSCtx_name = "JSCtxRegexpJSCtxDivOpJSCtxUnknown"

var _JSCtx_index = [...]uint8{0, 11, 21, 33}

func (i JSCtx) String() string {
	if i >= JSCtx(len(_JSCtx_index)-1) {
		return fmt.Sprintf("JSCtx(%d)", i)
	}
	return _JSCtx_name[_JSCtx_index[i]:_JSCtx_index[i+1]]
}
