// Code generated by "stringer -type URLPart"; DO NOT EDIT

package parse

import "fmt"

const _URLPart_name = "URLPartNoneURLPartPreQueryURLPartQueryOrFragURLPartUnknown"

var _URLPart_index = [...]uint8{0, 11, 26, 44, 58}

func (i URLPart) String() string {
	if i >= URLPart(len(_URLPart_index)-1) {
		return fmt.Sprintf("URLPart(%d)", i)
	}
	return _URLPart_name[_URLPart_index[i]:_URLPart_index[i+1]]
}
