// Code generated by gengoos.go using 'go generate'. DO NOT EDIT.

//go:build !android && linux
// +build !android,linux

package goos

const GOOS = `linux`

const Aix = 0
const Android = 0
const Darwin = 0
const Dragonfly = 0
const Freebsd = 0
const Hurd = 0
const Illumos = 0
const Ios = 0
const Js = 0
const Linux = 1
const Nacl = 0
const Netbsd = 0
const Openbsd = 0
const Plan9 = 0
const Solaris = 0
const Windows = 0
const Zos = 0
