package goroot

import (
	"strings"
)

var std = strings.Fields(`
archive/tar
archive/zip
bufio
bytes
compress/bzip2
compress/flate
compress/gzip
compress/lzw
compress/zlib
container/heap
container/list
container/ring
context
crypto
crypto/aes
crypto/cipher
crypto/des
crypto/dsa
crypto/ecdsa
crypto/ed25519
crypto/elliptic
crypto/hmac
crypto/internal/boring
crypto/internal/boring/bbig
crypto/internal/boring/sig
crypto/internal/edwards25519
crypto/internal/edwards25519/field
crypto/internal/nistec
crypto/internal/nistec/fiat
crypto/internal/randutil
crypto/internal/subtle
crypto/md5
crypto/rand
crypto/rc4
crypto/rsa
crypto/sha1
crypto/sha256
crypto/sha512
crypto/subtle
crypto/tls
crypto/x509
crypto/x509/internal/macos
crypto/x509/pkix
database/sql
database/sql/driver
debug/buildinfo
debug/dwarf
debug/elf
debug/gosym
debug/macho
debug/pe
debug/plan9obj
embed
embed/internal/embedtest
encoding
encoding/ascii85
encoding/asn1
encoding/base32
encoding/base64
encoding/binary
encoding/csv
encoding/gob
encoding/hex
encoding/json
encoding/pem
encoding/xml
errors
expvar
flag
fmt
go/ast
go/build
go/build/constraint
go/constant
go/doc
go/doc/comment
go/format
go/importer
go/internal/gccgoimporter
go/internal/gcimporter
go/internal/srcimporter
go/internal/typeparams
go/parser
go/printer
go/scanner
go/token
go/types
hash
hash/adler32
hash/crc32
hash/crc64
hash/fnv
hash/maphash
html
html/template
image
image/color
image/color/palette
image/draw
image/gif
image/internal/imageutil
image/jpeg
image/png
index/suffixarray
internal/abi
internal/buildcfg
internal/bytealg
internal/cfg
internal/cpu
internal/diff
internal/fmtsort
internal/fuzz
internal/goarch
internal/godebug
internal/goexperiment
internal/goos
internal/goroot
internal/goversion
internal/intern
internal/itoa
internal/lazyregexp
internal/lazytemplate
internal/nettrace
internal/obscuretestdata
internal/oserror
internal/pkgbits
internal/poll
internal/profile
internal/race
internal/reflectlite
internal/singleflight
internal/syscall/execenv
internal/syscall/unix
internal/sysinfo
internal/testenv
internal/testlog
internal/trace
internal/txtar
internal/unsafeheader
internal/xcoff
io
io/fs
io/ioutil
log
log/syslog
math
math/big
math/bits
math/cmplx
math/rand
mime
mime/multipart
mime/quotedprintable
net
net/http
net/http/cgi
net/http/cookiejar
net/http/fcgi
net/http/httptest
net/http/httptrace
net/http/httputil
net/http/internal
net/http/internal/ascii
net/http/internal/testcert
net/http/pprof
net/internal/socktest
net/mail
net/netip
net/rpc
net/rpc/jsonrpc
net/smtp
net/textproto
net/url
os
os/exec
os/exec/internal/fdtest
os/signal
os/signal/internal/pty
os/user
path
path/filepath
plugin
reflect
reflect/internal/example1
reflect/internal/example2
regexp
regexp/syntax
runtime
runtime/cgo
runtime/debug
runtime/internal/atomic
runtime/internal/math
runtime/internal/sys
runtime/metrics
runtime/pprof
runtime/race
runtime/trace
sort
strconv
strings
sync
sync/atomic
syscall
testing
testing/fstest
testing/internal/testdeps
testing/iotest
testing/quick
text/scanner
text/tabwriter
text/template
text/template/parse
time
time/tzdata
unicode
unicode/utf16
unicode/utf8
unsafe
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/chacha20poly1305
vendor/golang.org/x/crypto/cryptobyte
vendor/golang.org/x/crypto/cryptobyte/asn1
vendor/golang.org/x/crypto/curve25519
vendor/golang.org/x/crypto/curve25519/internal/field
vendor/golang.org/x/crypto/hkdf
vendor/golang.org/x/crypto/internal/poly1305
vendor/golang.org/x/crypto/internal/subtle
vendor/golang.org/x/net/dns/dnsmessage
vendor/golang.org/x/net/http/httpguts
vendor/golang.org/x/net/http/httpproxy
vendor/golang.org/x/net/http2/hpack
vendor/golang.org/x/net/idna
vendor/golang.org/x/net/nettest
vendor/golang.org/x/net/route
vendor/golang.org/x/sys/cpu
vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/text/transform
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/text/unicode/norm
cmd/addr2line
cmd/api
cmd/asm
cmd/asm/internal/arch
cmd/asm/internal/asm
cmd/asm/internal/flags
cmd/asm/internal/lex
cmd/buildid
cmd/cgo
cmd/compile
cmd/compile/internal/abi
cmd/compile/internal/amd64
cmd/compile/internal/arm
cmd/compile/internal/arm64
cmd/compile/internal/base
cmd/compile/internal/bitvec
cmd/compile/internal/compare
cmd/compile/internal/deadcode
cmd/compile/internal/devirtualize
cmd/compile/internal/dwarfgen
cmd/compile/internal/escape
cmd/compile/internal/gc
cmd/compile/internal/importer
cmd/compile/internal/inline
cmd/compile/internal/ir
cmd/compile/internal/liveness
cmd/compile/internal/logopt
cmd/compile/internal/mips
cmd/compile/internal/mips64
cmd/compile/internal/noder
cmd/compile/internal/objw
cmd/compile/internal/pkginit
cmd/compile/internal/ppc64
cmd/compile/internal/reflectdata
cmd/compile/internal/riscv64
cmd/compile/internal/s390x
cmd/compile/internal/ssa
cmd/compile/internal/ssagen
cmd/compile/internal/staticdata
cmd/compile/internal/staticinit
cmd/compile/internal/syntax
cmd/compile/internal/test
cmd/compile/internal/typebits
cmd/compile/internal/typecheck
cmd/compile/internal/types
cmd/compile/internal/types2
cmd/compile/internal/walk
cmd/compile/internal/wasm
cmd/compile/internal/x86
cmd/cover
cmd/dist
cmd/doc
cmd/fix
cmd/go
cmd/go/internal/auth
cmd/go/internal/base
cmd/go/internal/bug
cmd/go/internal/cache
cmd/go/internal/cfg
cmd/go/internal/clean
cmd/go/internal/cmdflag
cmd/go/internal/doc
cmd/go/internal/envcmd
cmd/go/internal/fix
cmd/go/internal/fmtcmd
cmd/go/internal/fsys
cmd/go/internal/generate
cmd/go/internal/get
cmd/go/internal/help
cmd/go/internal/imports
cmd/go/internal/list
cmd/go/internal/load
cmd/go/internal/lockedfile
cmd/go/internal/lockedfile/internal/filelock
cmd/go/internal/modcmd
cmd/go/internal/modconv
cmd/go/internal/modfetch
cmd/go/internal/modfetch/codehost
cmd/go/internal/modfetch/zip_sum_test
cmd/go/internal/modget
cmd/go/internal/modindex
cmd/go/internal/modinfo
cmd/go/internal/modload
cmd/go/internal/mvs
cmd/go/internal/par
cmd/go/internal/robustio
cmd/go/internal/run
cmd/go/internal/search
cmd/go/internal/str
cmd/go/internal/test
cmd/go/internal/test/internal/genflags
cmd/go/internal/tool
cmd/go/internal/trace
cmd/go/internal/vcs
cmd/go/internal/version
cmd/go/internal/vet
cmd/go/internal/web
cmd/go/internal/work
cmd/go/internal/workcmd
cmd/gofmt
cmd/internal/archive
cmd/internal/bio
cmd/internal/browser
cmd/internal/buildid
cmd/internal/codesign
cmd/internal/dwarf
cmd/internal/edit
cmd/internal/gcprog
cmd/internal/goobj
cmd/internal/metadata
cmd/internal/moddeps
cmd/internal/notsha256
cmd/internal/obj
cmd/internal/obj/arm
cmd/internal/obj/arm64
cmd/internal/obj/mips
cmd/internal/obj/ppc64
cmd/internal/obj/riscv
cmd/internal/obj/s390x
cmd/internal/obj/wasm
cmd/internal/obj/x86
cmd/internal/objabi
cmd/internal/objfile
cmd/internal/osinfo
cmd/internal/pkgpath
cmd/internal/quoted
cmd/internal/src
cmd/internal/sys
cmd/internal/test2json
cmd/internal/traceviewer
cmd/link
cmd/link/internal/amd64
cmd/link/internal/arm
cmd/link/internal/arm64
cmd/link/internal/benchmark
cmd/link/internal/dwtest
cmd/link/internal/ld
cmd/link/internal/loadelf
cmd/link/internal/loader
cmd/link/internal/loadmacho
cmd/link/internal/loadpe
cmd/link/internal/loadxcoff
cmd/link/internal/mips
cmd/link/internal/mips64
cmd/link/internal/ppc64
cmd/link/internal/riscv64
cmd/link/internal/s390x
cmd/link/internal/sym
cmd/link/internal/wasm
cmd/link/internal/x86
cmd/nm
cmd/objdump
cmd/pack
cmd/pprof
cmd/test2json
cmd/trace
cmd/vendor/github.com/google/pprof/driver
cmd/vendor/github.com/google/pprof/internal/binutils
cmd/vendor/github.com/google/pprof/internal/driver
cmd/vendor/github.com/google/pprof/internal/elfexec
cmd/vendor/github.com/google/pprof/internal/graph
cmd/vendor/github.com/google/pprof/internal/measurement
cmd/vendor/github.com/google/pprof/internal/plugin
cmd/vendor/github.com/google/pprof/internal/report
cmd/vendor/github.com/google/pprof/internal/symbolizer
cmd/vendor/github.com/google/pprof/internal/symbolz
cmd/vendor/github.com/google/pprof/internal/transport
cmd/vendor/github.com/google/pprof/profile
cmd/vendor/github.com/google/pprof/third_party/d3flamegraph
cmd/vendor/github.com/google/pprof/third_party/svgpan
cmd/vendor/github.com/ianlancetaylor/demangle
cmd/vendor/golang.org/x/arch/arm/armasm
cmd/vendor/golang.org/x/arch/arm64/arm64asm
cmd/vendor/golang.org/x/arch/ppc64/ppc64asm
cmd/vendor/golang.org/x/arch/x86/x86asm
cmd/vendor/golang.org/x/crypto/ed25519
cmd/vendor/golang.org/x/mod/internal/lazyregexp
cmd/vendor/golang.org/x/mod/modfile
cmd/vendor/golang.org/x/mod/module
cmd/vendor/golang.org/x/mod/semver
cmd/vendor/golang.org/x/mod/sumdb
cmd/vendor/golang.org/x/mod/sumdb/dirhash
cmd/vendor/golang.org/x/mod/sumdb/note
cmd/vendor/golang.org/x/mod/sumdb/tlog
cmd/vendor/golang.org/x/mod/zip
cmd/vendor/golang.org/x/sync/semaphore
cmd/vendor/golang.org/x/sys/internal/unsafeheader
cmd/vendor/golang.org/x/sys/unix
cmd/vendor/golang.org/x/term
cmd/vendor/golang.org/x/tools/cover
cmd/vendor/golang.org/x/tools/go/analysis
cmd/vendor/golang.org/x/tools/go/analysis/internal/analysisflags
cmd/vendor/golang.org/x/tools/go/analysis/internal/facts
cmd/vendor/golang.org/x/tools/go/analysis/passes/asmdecl
cmd/vendor/golang.org/x/tools/go/analysis/passes/assign
cmd/vendor/golang.org/x/tools/go/analysis/passes/atomic
cmd/vendor/golang.org/x/tools/go/analysis/passes/bools
cmd/vendor/golang.org/x/tools/go/analysis/passes/buildtag
cmd/vendor/golang.org/x/tools/go/analysis/passes/cgocall
cmd/vendor/golang.org/x/tools/go/analysis/passes/composite
cmd/vendor/golang.org/x/tools/go/analysis/passes/copylock
cmd/vendor/golang.org/x/tools/go/analysis/passes/ctrlflow
cmd/vendor/golang.org/x/tools/go/analysis/passes/errorsas
cmd/vendor/golang.org/x/tools/go/analysis/passes/framepointer
cmd/vendor/golang.org/x/tools/go/analysis/passes/httpresponse
cmd/vendor/golang.org/x/tools/go/analysis/passes/ifaceassert
cmd/vendor/golang.org/x/tools/go/analysis/passes/inspect
cmd/vendor/golang.org/x/tools/go/analysis/passes/internal/analysisutil
cmd/vendor/golang.org/x/tools/go/analysis/passes/loopclosure
cmd/vendor/golang.org/x/tools/go/analysis/passes/lostcancel
cmd/vendor/golang.org/x/tools/go/analysis/passes/nilfunc
cmd/vendor/golang.org/x/tools/go/analysis/passes/printf
cmd/vendor/golang.org/x/tools/go/analysis/passes/shift
cmd/vendor/golang.org/x/tools/go/analysis/passes/sigchanyzer
cmd/vendor/golang.org/x/tools/go/analysis/passes/stdmethods
cmd/vendor/golang.org/x/tools/go/analysis/passes/stringintconv
cmd/vendor/golang.org/x/tools/go/analysis/passes/structtag
cmd/vendor/golang.org/x/tools/go/analysis/passes/testinggoroutine
cmd/vendor/golang.org/x/tools/go/analysis/passes/tests
cmd/vendor/golang.org/x/tools/go/analysis/passes/unmarshal
cmd/vendor/golang.org/x/tools/go/analysis/passes/unreachable
cmd/vendor/golang.org/x/tools/go/analysis/passes/unsafeptr
cmd/vendor/golang.org/x/tools/go/analysis/passes/unusedresult
cmd/vendor/golang.org/x/tools/go/analysis/unitchecker
cmd/vendor/golang.org/x/tools/go/ast/astutil
cmd/vendor/golang.org/x/tools/go/ast/inspector
cmd/vendor/golang.org/x/tools/go/cfg
cmd/vendor/golang.org/x/tools/go/types/objectpath
cmd/vendor/golang.org/x/tools/go/types/typeutil
cmd/vendor/golang.org/x/tools/internal/analysisinternal
cmd/vendor/golang.org/x/tools/internal/lsp/fuzzy
cmd/vendor/golang.org/x/tools/internal/typeparams
cmd/vendor/golang.org/x/xerrors
cmd/vendor/golang.org/x/xerrors/internal
cmd/vet
`)

