// auto generated by go tool dist

package schedinit

const DefaultGoroot = `/Users/michaelmatloob/Desktop/tmp2`
const TheVersion = `devel +4227607 Mon Jan 19 08:06:27 2015 -0800`

var buildVersion = TheVersion
