// auto generated by go tool dist

package schedinit

const DefaultGoroot = `/Users/michaelmatloob/Desktop/tmp`
const TheVersion = `devel +455f822 Wed Jan 21 22:02:35 2015 -0800`

var buildVersion = TheVersion
