// auto generated by go tool dist

package schedinit

const DefaultGoroot = `/Users/michaelmatloob/refactoring/surgery`
const TheVersion = `devel +a517110 Sun Jan 25 13:45:35 2015 -0800`

var buildVersion = TheVersion
