// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by genflags.go — DO NOT EDIT.

package test

// passFlagToTest contains the flags that should be forwarded to
// the test binary with the prefix "test.".
var passFlagToTest = map[string]bool{
	"bench":                true,
	"benchmem":             true,
	"benchtime":            true,
	"blockprofile":         true,
	"blockprofilerate":     true,
	"count":                true,
	"coverprofile":         true,
	"cpu":                  true,
	"cpuprofile":           true,
	"failfast":             true,
	"list":                 true,
	"memprofile":           true,
	"memprofilerate":       true,
	"mutexprofile":         true,
	"mutexprofilefraction": true,
	"outputdir":            true,
	"parallel":             true,
	"run":                  true,
	"short":                true,
	"shuffle":              true,
	"timeout":              true,
	"trace":                true,
	"v":                    true,
}

var passAnalyzersToVet = map[string]bool{
	"cgocall":                    true,
	"stringintconv":              true,
	"asmdecl":                    true,
	"composites.whitelist":       true,
	"unreachable":                true,
	"tests":                      true,
	"unusedresult.stringmethods": true,
	"assign":                     true,
	"composites":                 true,
	"framepointer":               true,
	"stdmethods":                 true,
	"sigchanyzer":                true,
	"atomic":                     true,
	"httpresponse":               true,
	"nilfunc":                    true,
	"printf.funcs":               true,
	"unusedresult":               true,
	"unmarshal":                  true,
	"unusedresult.funcs":         true,
	"bools":                      true,
	"buildtag":                   true,
	"errorsas":                   true,
	"lostcancel":                 true,
	"structtag":                  true,
	"printf":                     true,
	"shift":                      true,
	"testinggoroutine":           true,
	"unsafeptr":                  true,
	"copylocks":                  true,
	"ifaceassert":                true,
	"loopclosure":                true,
}
