// generated by gengoos.go using 'go generate'

package base

const theGoarch = `amd64`

const goarch_386 = 0
const goarch_amd64 = 1
const goarch_amd64p32 = 0
const goarch_arm = 0
const Goarch_arm64 = 0
