// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.exectraceredesign
// +build !goexperiment.exectraceredesign

package goexperiment

const ExecTraceRedesign = false
const ExecTraceRedesignInt = 0
