// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.atomicaggregates
// +build !goexperiment.atomicaggregates

package goexperiment

const AtomicAggregates = false
const AtomicAggregatesInt = 0
