// Code generated by mkconsts.go. DO NOT EDIT.

//go:build !goexperiment.inlinerrevamp
// +build !goexperiment.inlinerrevamp

package goexperiment

const InlinerRevamp = false
const InlinerRevampInt = 0
